version: '3.8'

services:
  payment_service:
    build:
      context: ./app
      dockerfile: ../Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENV_FILE=.env
    volumes:
      - .:/app
    networks:
      - payment_network

networks:
  payment_network:
    driver: bridge