version: '3.8'
services:
  db-payment:
    image: mongo:8.2
    container_name: MongoDB-Payment
    environment:
      MONGO_INITDB_DATABASE: db-payment
    ports:
      - "27017:27017"
    volumes:
      - mongodb_payment_data:/data/db
    restart: unless-stopped
    networks:
      - rental-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 2s
      retries: 5
      start_period: 20s

  payment_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rental-payment-service
    restart: unless-stopped
    ports:
      - "8004:8004"
    env_file:
      - ./.env.payment
    depends_on:
      db-payment:
        condition: service_healthy
    networks:
      - rental-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8004/api/v1/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongodb_payment_data:
    driver: local

networks:
  rental-network:
    driver: bridge