version: '3.8'

services:
  vehicle_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vehicle-service-server2
    network_mode: host
    environment:
      - MONGO_URI=mongodb://100.69.63.99:27017/rental
      - PORT=8002
      - API_GATEWAY_URL=http://100.69.63.99:8000
      - USER_SERVICE_URL=http://100.69.63.99:8001
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8002/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
